name: kousik_portfolio
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  flutter_bloc: ^6.1.1
  font_awesome_flutter: ^8.10.0
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  json_annotation: ^3.1.1
  styled_widget: ^0.2.2
  timeline_tile: ^1.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.4
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/
